# Check https://circleci.com/docs/2.0/language-javascript/ for more details

cache_key: &cache_key
  v1-dependencies-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "esy.lock.json" }}

steps: &steps
- checkout
- run:
    name: Setup environment variables
    command: |
      echo 'export NPM_CONFIG_PREFIX="$HOME/.npm-global"' >> $BASH_ENV
      echo 'export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"' >> $BASH_ENV

# Download and cache dependencies
- restore_cache:
    keys:
    - *cache_key

- run: npm install -g esy
- run: esy install
- run: esy build

- save_cache:
    paths:
      - ~/.esy
    key: *cache_key

- run:
    name: Producing release
    command: make build-release
- run:
    name: Preparing release tarball
    command: mv "_release/$(cd _release && npm pack 2>/dev/null)" _release/reason-cli.tgz
- run:
    name: Installing release
    command: npm install -g ./_release/reason-cli.tgz
- run:
    name: Testing release
    command: bash ./test.sh

- store_artifacts:
    path: _release/reason-cli.tgz
    destination: reason-cli.tgz

environment: &environment
- TERM: dumb

working_directory: &working_directory
  ~/repo

version: 2
jobs:
  macos:
    macos:
      xcode: "9.0"

    working_directory: *working_directory
    environment: *environment
    steps: *steps

  linux:
    docker:
    - image: circleci/node:8-stretch-browsers

    working_directory: *working_directory
    environment: *environment
    steps: *steps

workflows:
  version: 2
  build-deploy:
    jobs:
    - linux
    - macos
